language: python
python:
  -  "3.8"
install:
  - pip install poetry
  - pip install twisted
  - pip install behave
script:
  - python -m unittest tests.test_klick_brick_cli
  - behave

cache:
  directories:
  - $HOME/.cache/pre-commit
